# Generated by Django 5.0.9 on 2024-09-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='nivel',
            new_name='nivel_aluno',
        ),
    ]
