# Generated by Django 5.0.9 on 2024-09-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_rename_nivel_cursos_nivel_aluno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
